version: '3'
networks:
  unbound:
services:
  ukc-ep:
    container_name: "ukc-ep-vhsm"
    image: "${UNBOUND_REPO:-unboundukc}/ukc-server:${UB_VER:-latest}.vhsm"
    restart: always
    ports:
      - "9021:9001"
      - "9022:9002"
      - "8082:8080"
      - "9443:443"
    command: ["ep", "ukc-partner", "ukc-aux"]
    hostname: ukc-ep
    env_file:
      settings.env
    networks:
      - unbound
    deploy:
      resources:
        limits:
          memory: 450m
  ukc-partner:
    container_name: "ukc-partner-vhsm"
    image: "${UNBOUND_REPO:-unboundukc}/ukc-server:${UB_VER:-latest}.vhsm"
    restart: always
    command: ["partner", "ukc-ep", "ukc-aux"]
    hostname: ukc-partner
    depends_on:
      - "ukc-ep"
    ports:
      - "9023:9002"
    networks:
      - unbound
    deploy:
      resources:
        limits:
          memory: 450m
  ukc-aux:
    container_name: "ukc-aux-vhsm"
    image: "${UNBOUND_REPO:-unboundukc}/ukc-server:${UB_VER:-latest}.vhsm"
    restart: always
    command: ["aux", "ukc-ep", "ukc-partner"]
    hostname: ukc-aux
    depends_on:
      - "ukc-ep"
      - "ukc-partner"
    ports:
      - "9024:9001"
    networks:
      - unbound
    deploy:
      resources:
        limits:
          memory: 450m
  ukc-client:
    container_name: "ukc-client-vhsm"
    image: "${UNBOUND_REPO:-unboundukc}/ukc-client:${UB_VER:-latest}.vhsm"
    restart: always
    hostname: ukc-client
    depends_on:
      - "ukc-ep"
    ports:
      - "8081:8081"
      - "8444:8443"
    env_file:
      settings.env
    networks:
      - unbound
    deploy:
      resources:
        limits:
          memory: 450m
